### ISSUE TITLE
dry run of new fabric8 release workflow fails on Quickstarts :: Karaf4 :: Camel Log

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4683]
```
Failed to execute goal org.jolokia:docker-maven-plugin:0.13.2:build (default-cli) on project quickstart-karaf4-camellog: Failed to create assembly for docker image: Error creating assembly archive docker: Failed to read filesystem attributes for: /var/jenkins_home/quickstarts/quickstarts/karaf4/camel-log/target/quickstart-karaf4-camellog-1.0.20.tar.gz with mode dir -> [Help 1]
```

```
[INFO] Fabric8 :: Quickstarts :: Java :: Camel CDI ........ SUCCESS [ 21.042 s]
[INFO] Fabric8 :: Quickstarts :: Java :: Camel CDI and ActiveMQ SUCCESS [ 19.550 s]
[INFO] Fabric8 :: Quickstarts :: Java :: Camel Spring ..... SUCCESS [ 17.237 s]
[INFO] Fabric8 :: Quickstarts :: Java :: CXF JAX-RS CDI ... SUCCESS [ 23.886 s]
[INFO] Fabric8 :: Quickstarts :: Java :: JGroups Greeter .. SUCCESS [ 17.731 s]
[INFO] Fabric8 :: Quickstarts :: Java :: Simple fat jar ... SUCCESS [ 30.869 s]
[INFO] Fabric8 :: Quickstarts :: Java :: Simple main class  SUCCESS [ 16.487 s]
[INFO] Fabric8 :: Quickstarts :: Karaf :: Parent .......... SUCCESS [  0.073 s]
[INFO] Fabric8 :: Quickstarts :: Karaf :: Camel using ActiveMQ SUCCESS [ 35.398 s]
[INFO] Fabric8 :: Quickstarts :: Karaf :: Camel Log ....... SUCCESS [ 27.557 s]
[INFO] Fabric8 :: Quickstarts :: Karaf :: Camel Rest using SQL SUCCESS [ 33.196 s]
[INFO] Fabric8 :: Quickstarts :: Karaf :: CXF RESTful WebService SUCCESS [ 34.366 s]
[INFO] Fabric8 :: Quickstarts :: Karaf4 :: Parent ......... SUCCESS [  0.111 s]
[INFO] Fabric8 :: Quickstarts :: Karaf4 :: Camel Log ...... FAILURE [  0.450 s]
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: Parent .... SKIPPED
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: WebMVC .... SKIPPED
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: WebMVC IP . SKIPPED
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: Camel ..... SKIPPED
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: ActiveMQ .. SKIPPED
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: Keycloak .. SKIPPED
[INFO] Fabric8 :: Quickstarts :: War :: Wildfly ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20:54 min
[INFO] Finished at: 2015-09-03T16:07:27+00:00
[INFO] Final Memory: 643M/2049M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.2:build (default-cli) on project quickstart-karaf4-camellog: Failed to create assembly for docker image: Error creating assembly archive docker: Failed to read filesystem attributes for: /var/jenkins_home/quickstarts/quickstarts/karaf4/camel-log/target/quickstart-karaf4-camellog-1.0.20.tar.gz with mode dir -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :quickstart-karaf4-camellog
Running: Set environment variables : Body : End
Running: Set environment variables : End
Running: Allocate workspace : Body : End
Running: Allocate workspace : End
Running: Allocate node : Body : End
Running: Allocate node : End
Running: End of Workflow
ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by rawlingsj** [comment]
Temporarily commented out as agreed with Dhiraj Bokde.

**Comment by dhirajsb** [comment]
Fixed with PR https://github.com/fabric8io/quickstarts/pull/671

**Comment by rawlingsj** [comment]
@dhirajsb still getting an issue with that quickstart unfortunately.  I'm going to disable the karaf 4 quickstart for this release and we can take another look at the issue.

```
The command [/bin/sh -c tar xzf /opt/jboss/quickstart-karaf4-camellog-2.3-SNAPSHOT.tar.gz -C /opt/jboss] returned a non-zero code: 2
```
```
[INFO] Fabric8 :: Quickstarts :: Karaf4 :: Parent ......... SUCCESS [  0.057 s]
[INFO] Fabric8 :: Quickstarts :: Karaf4 :: Camel Log ...... FAILURE [03:24 min]
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: Parent .... SKIPPED
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: WebMVC .... SKIPPED
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: WebMVC IP . SKIPPED
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: Camel ..... SKIPPED
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: ActiveMQ .. SKIPPED
[INFO] Fabric8 :: Quickstarts :: Spring-Boot :: Keycloak .. SKIPPED
[INFO] Fabric8 :: Quickstarts :: War :: Wildfly ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24:08 min
[INFO] Finished at: 2015-09-04T10:41:32+00:00
[INFO] Final Memory: 669M/1751M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.2:build (default-cli) on project quickstart-karaf4-camellog: The command [/bin/sh -c tar xzf /opt/jboss/quickstart-karaf4-camellog-2.3-SNAPSHOT.tar.gz -C /opt/jboss] returned a non-zero code: 2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :quickstart-karaf4-camellog
```

**Comment by davsclaus** [comment]
The karaf 4 quickstart has been removed yesterday.
