### ISSUE TITLE
console shows no namespaces on kubernetes server

### ISSUE THREAD

**Issue by MarWestermann** [fabric8io/fabric8#5620]
I setup a kubernetes server on a digital ocean server. After that I did the following steps to give the fabric8 console a try:

installed fabric8 console by:
kubectl create -f http://central.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.104/console-kubernetes-2.2.104-kubernetes.json

expose the port so it is available from internet:
kubectl expose rc fabric8 --port=9090 --target-port=9090 --public-ip="46.101.140.18" --name="fabric8-public"

Here are the logs of the fabric8 pod:
http://pastebin.com/L7JN8qmm

**Comment by rawlingsj** [comment]
Sorry for the slow response.  I'll spin up a vanilla kubernetes instance today so we can look into it.

**Comment by rawlingsj** [comment]
I've recreated the problem.  @gashcrumb if you get time later can we have a look at what might be the problem?  I'll ping you the instance details.  I cant see any obvious issues in the javascript console so not too sure

**Comment by MarWestermann** [comment]
the first problem was, that not the fabric8 console needs to be exported to the outer world but instead the k8s api.

After exposing the k8s api via kubectl proxy, this url is working: http://46.101.140.18:9090/api/v1/proxy/namespaces/default/services/fabric8/kubernetes/namespace/default/apps?q=

but there is still a bug getting the namespaces:

that is why http://46.101.140.18:9090/api/v1/proxy/namespaces/default/services/fabric8/ is still showing: There are no namespaces currently available.

James Strachan wrote in IRC: there's a bug, we need to GET /api/v1/namespaces too on k8s to avoid the websocket issue for switching between namespaces

**Comment by gashcrumb** [comment]
Fixed here -> https://github.com/hawtio/hawtio-kubernetes/commit/6a267a191fdee4e326893d4e9dc693d8134ccdbe

**Comment by rawlingsj** [comment]
released and tested successfully against GKE so you should be good to go now @MarWestermann

**Comment by rawlingsj** [comment]
nice one @gashcrumb!

**Comment by rawlingsj** [comment]
Which version are you using?  We fixed an [issue](https://github.com/fabric8io/fabric8/issues/5344) last week that hopefully solves this..

To remove the old console and add the latest version...
```
kubectl delete all -l provider=fabric8
kubectl delete serviceaccount fabric8
kubectl create -f http://repo1.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.105/console-kubernetes-2.2.105-kubernetes.json
```

**Comment by solstarz** [comment]
Hi,

I tried the newest version but im still getting this error:
There are no namespaces currently available.

Im trying to get this running on GKE.
I dont know where its actually failing.

**Comment by rawlingsj** [comment]
I've just resinstalled 2.2.105 using the commands above and I can definitely see the namespaces using the URL `https://[gke-apiserver-ip]/api/v1/proxy/namespaces/default/services/fabric8` and logging in with the admin credentials in  `~/.kube/config`

Does `kubectl get rc` show the version you expect in the RC labels?

I wonder if there's any errors in the javascript console?  You can also select the network tab and filter on `namespace` to see if there's any network erorrs.  Also what browser are you using?  I'm using Chrome here.

**Comment by gashcrumb** [comment]
@solstarz yeah, just to be on the safe side clear your browser cache or try using incognito mode, also worth verifying in the user menu at the top-right, click 'preferences' and that should put you on the 'about' page which lists all the versions of what's running in the console

**Comment by solstarz** [comment]
This is the output kubectl get rc.

fabric8               fabric8-container   fabric8/fabric8-console:2.2.105               group=io.fabric8.apps,project=console,provider=fabric8,version=2.2.105

Im using chrome aswell.
I've checked the network tab and filtered on namespace but for what i can see no errors.

**Comment by solstarz** [comment]
@gashcrumb I cleared the cache. 
This is the version i have at the moment:

About fabric8-console

Version: 1.0.73

**Comment by solstarz** [comment]
Hi guys,

Could this be the issue?

WebSocket connection to 'ws://api ip/api/v1/namespaces?watch=true&access_token' failed: Establishing a tunnel via proxy server failed.

**Comment by rawlingsj** [comment]
yeah it looks like the api server ip address is missing

**Comment by jimmidyson** [comment]
I assume @solstarz just censored that ;)

**Comment by solstarz** [comment]
Yes its censored...hihi

**Comment by jimmidyson** [comment]
@solstarz So do you run behind a http proxy? Does your proxy support websocket proxying? If not there's not much we can do I'm afraid.

**Comment by solstarz** [comment]
Yep you are right proxy issues.

Tried without a proxy and it works.

Thanks @jimmidyson
