### ISSUE TITLE
logging app doesn't run from the console

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5862]
When running the logging app from the console I see the errors below however running the yaml from the command line works.
```
kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: 'Service "elasticsearch" is invalid: spec.clusterIP: Invalid value: "": field is immutable'
reason: Invalid
details:
  name: elasticsearch
  kind: Service
  causes:
    - reason: FieldValueInvalid
      message: 'Invalid value: "": field is immutable'
      field: spec.clusterIP
code: 422
```
```
kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: 'Service "kibana" is invalid: spec.clusterIP: Invalid value: "": field is immutable'
reason: Invalid
details:
  name: kibana
  kind: Service
  causes:
    - reason: FieldValueInvalid
      message: 'Invalid value: "": field is immutable'
      field: spec.clusterIP
code: 422
```

**Comment by rawlingsj** [comment]
@jimmidyson are you aware of this issue?  Is it related to the new fluentd daemon set?

**Comment by jimmidyson** [comment]
I assume so but have no idea why it works from the command line & not via the console. I assume the console doesn't support all types or something like that?

**Comment by gashcrumb** [comment]
Wonder if I need to just strip that attribute out of the yaml/json before
posting?

**Comment by jimmidyson** [comment]
Oh sorry now I read the bug report.... yeah you need to strip that out or update it with the current cluster IP.

**Comment by gashcrumb** [comment]
@jimmidyson noticed also the console won't deploy the fluentd daemonset as we don't have support in hawtio-kubernetes-api yet for it.  What's the URL pattern for those?

**Comment by gashcrumb** [comment]
Hmm, so stripping that out, but noticed that I can still get this error at least when that service already exists, even though spec.clusterIP wasn't even set in the object we're trying to post.  I guess we could first delete and then put the new object rather than relying on 'put' to replace it, not sure...

**Comment by gashcrumb** [comment]
@rawlingsj maybe try running 'latest' of the console image and see if that works for you?  Figure it's not worth doing a new release if this still doesn't work.

**Comment by rawlingsj** [comment]
perfect thanks, will do - I'll give it a crack this evening and report back or kick off a release if it works.

**Comment by rawlingsj** [comment]
I think it's still a problem.  I've put the console:latest on our UX env - I just tried to run the logging app and seem to get the same problem.  http://fabric8.ux.fabric8.io/
In the JS console I see..
```
libs.js:62538 Error: Unknown kind: daemonsets
    at i.getPrefix (libs.js:177079)
    at new i (libs.js:176944)
    at e.create (libs.js:177283)
    at Object.Be [as createKubernetesClient] (libs.js:191847)
    at libs.js:205735
    at it (libs.js:80311)
    at Function.<anonymous> (libs.js:82367)
    at v (libs.js:205707)
    at h.t.deployTemplate (libs.js:205700)
    at libs.js:63306
```

**Comment by gashcrumb** [comment]
Clear your cache?  Shouldn't be getting that exception...

**Comment by rawlingsj** [comment]
yeah I did and just double checked - also checked the latest console is pulled on that ux box too.  I've probably missed something but I'm not seeing what.

**Comment by gashcrumb** [comment]
Huh, that's lame...  K will look into it more tomorrow :-)

**Comment by gashcrumb** [comment]
Phew, found the culprit, had forgotten to rebuild hawtio-kubernetes before committing, tested and this should work now.

**Comment by rawlingsj** [comment]
fixed with the latest console release - nice one @gashcrumb

**Comment by tdcox** [comment]
Something is unfortunately still broken here, using gofabric8 0.4.4:

Deploying the logging app via the console results in no pods being deployed and no containers attempting to start. Services appear to be created.

If I launch each YAML config individually with 'oc create', all the components appear to launch and stay up, although fluentd takes a very long time to start. No data flowing into Kibana, however. I can see .kibana and logstash indexes in elasticsearch.
