### ISSUE TITLE
jenkins service accunt doesnt get created 1st time running on vanilla kubernetes

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5964]
On a clean fabric8 environment with vanilla kubernetes the Jenkins service account doesn't get created the first time the cd-pipeline is run, however running the app a second time it does get created.  Below is the screen shots, I couldn't see anything related to the SA in the javascript console so not too sure where to look for more info?

1st time running cd-pipeline
<img width="514" alt="screenshot 2016-04-25 11 47 47" src="https://cloud.githubusercontent.com/assets/1457180/14784906/cabf3a04-0aef-11e6-91ef-54247330c398.png">

2nd time running cd-pipeline
<img width="509" alt="screenshot 2016-04-25 11 48 30" src="https://cloud.githubusercontent.com/assets/1457180/14784915/d33169e6-0aef-11e6-94bc-61868796154c.png">

**Comment by gashcrumb** [comment]
Fixed this late last week, might not have made it into a release yet...

**Comment by jmlambert78** [comment]
It is still not working on a today's instlal of origin, not vanilla k8S only

**Comment by rawlingsj** [comment]
ok nice one @gashcrumb - it might be worth me kicking off a potential release tonight and have it staged in the test environments for a bit of QA in the morning then

**Comment by jstrachan** [comment]
yeah - we've not released the console in about 5 days; so we probably need a new release

**Comment by rawlingsj** [comment]
this has been released now
