### ISSUE TITLE
"Waiting for next available executor"

### ISSUE THREAD

**Issue by fabriziocucci** [fabric8io/fabric8#6661]
I'm on OSX El Capitan and I'm definitely new of fabric8, so bear with me.

I started with [this](https://github.com/fabric8io/fabric8/issues/6395#issuecomment-269505640), followed by [this](https://github.com/fabric8io/fabric8/issues/6658#issuecomment-269101738).

Now if I run:
`kubectl get pods`

I get the following:
```
configmapcontroller-3703242456-f9ctf       1/1       Running   3          15h
exposecontroller-2934573704-pp18d          1/1       Running   3          15h
fabric8-3192130638-a4gq5                   2/2       Running   6          15h
fabric8-docker-registry-1981087684-yyxee   1/1       Running   3          15h
fabric8-forge-3730694965-h7w6b             1/1       Running   1          15h
gogs-3384048149-qru2j                      1/1       Running   2          15h
jenkins-1661962136-mgdsr                   1/1       Running   2          15h
nexus-3628846063-fi18n                     1/1       Running   3          15h
```

I've created a new *Java WAR* project in the *default* team with the *CanaryRelease*. The following two commits have been automatically generated:
```
devops-edit --from=fabric8/tomcat-8 --pipeline=maven/CanaryRelease/Jenkinsfile
gogsadmin committed
```
```
project-new --type=Java Web Application (WAR) --topLevelPackage=org.example --version=1.0.0-SNAPSHOT --stack=None --targetLocation=/tmp/fabric8-forge/user/gogsadmin --named=third --buildSystem=Maven
gogsadmin committed 
```
 
The first build is triggered and the output is the following:
```
...
First time build. Skipping changelog.
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor 
```
...and it stays like this forever!

In the Jenkinksfile, I noticed this:
```
...
def label = "buildpod.${env.JOB_NAME}.${env.BUILD_NUMBER}".replace('-', '_').replace('/', '_')
...
node(label) {
...
}
```
But if I open Jenkins, I can see that there is only the master node and the build is blocked in the queue (because there is no node with that label?).

Any help would be much appreciated! :smile:

**Comment by donshoarma** [comment]
We have the same issue:

When running a build I ran into the following problem:
(Pipeline logging)

    /usr/bin/git rev-list 057e306664e9afbb8e2d7bc08cc83b98871fad56 # timeout=10
    [Pipeline] podTemplate
    [Pipeline] {
    [Pipeline] node
    Still waiting to schedule task
    Waiting for next available executor

(Jenkins system logging)
Dec 29, 2016 12:13:09 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision

Excess workload after pending Spot instances: 1

Dec 29, 2016 12:13:09 PM WARNING org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision

Failed to count the # of live instances on Kubernetes
java.lang.NullPointerException
at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.addProvisionedSlave(KubernetesCloud.java:639)
at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.provision(KubernetesCloud.java:510)
at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:701)
at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:307)
at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:60)
at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:798)
at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by amb-it-ion** [comment]
Same here, windows host with minikube virtualbox client.

**Comment by amb-it-ion** [comment]
I think this might be related to a [known jenkins kubernetes-plugin bug](https://issues.jenkins-ci.org/browse/JENKINS-40452) that got introduced with kubernetes 1.5.1?

**Comment by amb-it-ion** [comment]
yep, manually updating the plugin (on <jenkins-url>/pluginManager/) fixed the problem.

**Comment by amb-it-ion** [comment]
any estimates on when that next release might happen?

**Comment by rawlingsj** [comment]
The aim is by the morning.  I've successfully tested a java project pipeline on minikube v0.14.0 locally.  Everything is pushed and the release train that contains various fixes is chugging away.  

Provided there's no more significant issues that are found relating to the kubernetes 1.5.x upgrade fabric8's own release pipelines should finish later tonight / early tomorrow.

**Comment by amb-it-ion** [comment]
nice - great work! :)

**Comment by rawlingsj** [comment]
@amb-it-ion scrap that - the release pipeline is stuck  ATM unfortunately.  This may get sorted soon but it's difficult to say when as most folks are on holidays for the festive season.  To track the current block in the pipeline you can watch https://github.com/fabric8io/fabric8-maven-plugin/pull/749

**Comment by fabriziocucci** [comment]
For some reason, I can't update the Kubernetes plugin in Jenkins:
```
Latest version: 0.10
Installed version: 0.10-SNAPSHOT (private-6ae0cf4c-iocanel)
```

I tried both automatically and manually, but after the Jenkins restart the plugin seems to be still the old one (i.e. the plugin is still visible in the `Updates` tab of the `Plugin Manager`).

**Comment by rawlingsj** [comment]
BTW this should have been fixed a few releases back sorry, please reopen if there's any problems.

**Comment by jackjacek** [comment]
I'm on kubernetes 1.5.1 and kubernetes-pugin 0.10-SNAPSHOT (private-70e60d4e-jamesrawlings). If I push to 50+ repos simultaneously the pipeline gets stuck within minutes. Any suggestions?

**Comment by ikke44** [comment]
I still experience this very issue although I am on the latest version of Fabric8 (as per https://raw.githubusercontent.com/fabric8io/gofabric8/master/version/VERSION) with a recent Minikube:
```
$ gofabric8 version
gofabric8, version 0.4.121 (branch: 'master', revision: '835aa16')
  build date:       '20170306-10:48:35'
  go version:       '1.7.1'
$ minikube version
minikube version: v0.17.1

```
You can very easily reproduce this error by creating a 'Pipeline script from SCM' Jenkins job that tries to build the 'Release' Maven sample:
1/ Repository URL = https://github.com/fabric8io/fabric8-jenkinsfile-library.git
2/ Script path = \maven\Release\Jenkinsfile

It results in this 'Console Output' in Jenkins that continues 'forever':
```
Started by user anonymous
 > /usr/bin/git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-jenkinsfile-library.git # timeout=10
Fetching upstream changes from https://github.com/fabric8io/fabric8-jenkinsfile-library.git
 > /usr/bin/git --version # timeout=10
 > /usr/bin/git fetch --tags --progress https://github.com/fabric8io/fabric8-jenkinsfile-library.git +refs/heads/*:refs/remotes/origin/*
 > /usr/bin/git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > /usr/bin/git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision cce86bc9ff7d9bc0c30996d4a4b1c7f4c26924ca (refs/remotes/origin/master)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f cce86bc9ff7d9bc0c30996d4a4b1c7f4c26924ca
 > /usr/bin/git rev-list cce86bc9ff7d9bc0c30996d4a4b1c7f4c26924ca # timeout=10
Loading library github.com/fabric8io/fabric8-pipeline-library@master
 > /usr/bin/git rev-parse --is-inside-work-tree # timeout=10
Setting origin to https://github.com/fabric8io/fabric8-pipeline-library.git
 > /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
Fetching origin...
Fetching upstream changes from origin
 > /usr/bin/git --version # timeout=10
 > /usr/bin/git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/*
 > /usr/bin/git rev-parse master^{commit} # timeout=10
 > /usr/bin/git rev-parse origin/master^{commit} # timeout=10
 > /usr/bin/git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git
 > /usr/bin/git --version # timeout=10
 > /usr/bin/git fetch --tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision fa5faac2a37f695fc43bbdb76e55ab406bc3f121 (master)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f fa5faac2a37f695fc43bbdb76e55ab406bc3f121
 > /usr/bin/git rev-list fa5faac2a37f695fc43bbdb76e55ab406bc3f121 # timeout=10
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor
```

**Comment by jwausle** [comment]
I still experience the issue too. 
- with same versions like @ikke44  above
